### ISSUE TITLE
undefined reference to `assure'

### ISSUE THREAD

**Issue by firashacker** [tihmstar/usbmuxd2#11]
Hi tihmstart i installed all the requirements to compile this repo but at the end i got this issue 
#/usr/bin/ld: /home/firas/Downloads/usbmuxd2/usbmuxd2/log.c:58: undefined reference to #`assure'
#collect2: error: ld returned 1 exit status
#make[2]: *** [Makefile:530: usbmuxd] Error 1
#make[2]: Leaving directory '/home/firas/Downloads/usbmuxd2/usbmuxd2'
#make[1]: *** [Makefile:432: all-recursive] Error 1
#make[1]: Leaving directory '/home/firas/Downloads/usbmuxd2'
#make: *** [Makefile:364: all] Error 2

can you please help me solving that or check it if you can update the source and solve it 

thank you

**Comment by firashacker** [comment]
i think the issue is in /usbmuxd2/log.c file

**Comment by firashacker** [comment]
yep you called the function assure without crating it at the first so i created an empty function and combile the code again and it works .... idon't want logs anyway

**Comment by MarSoft** [comment]
Obviously this should have been a call to a macro from `libgeneral`.
This issue is still to be fixed.
