### ISSUE TITLE
Connection drops when phone locks

### ISSUE THREAD

**Issue by johnfgoodman** [tihmstar/usbmuxd2#20]
I am not sure if this is usbmuxd2, libimobiledevice or ios issue, but when I mount my ios 15 device via wifi, it works fine as long as my screen stays on and phone is unlocked. But when my phone locks, the mount fails and when I try to access it I get an Input/output error and I must unmount, restart usbmuxd service and remount. Is this expected behavior, or is there a workaround? When I run idevicebackup2 vs. ifuse, the phone is able to continue syncing even when the phone is locked, so it seems like it should be possible when mounting via ifuse?

**Comment by tihmstar** [comment]
Code has undergone a major rewrite since this issue was created.
