### ISSUE TITLE
package requirements(libgeneral  >= 39) were not met

### ISSUE THREAD

**Issue by sweetorange2022** [tihmstar/usbmuxd2#21]
when i execute : ./autogen.sh  ,happen  the error: 
checking for libgeneral...   no
configure:error: package requirements(libgeneral  >= 39) were not met:

what should i do for it?

**Comment by KantBStoppd** [comment]
I had the same issue. I ran these commands to fix it 

sudo git clone https://github.com/tihmstar/libgeneral.git
cd libgeneral
sudo ./autogen.sh
sudo make
sudo make install

**Comment by sweetorange2022** [comment]
configure:error: package requirements(libgeneral >= 39) were not met is disapper and i meet **other issue**:
error wifi support requested but no wifi backebd could not be found.
what should i do for it?

**Comment by KantBStoppd** [comment]
Have you installed all of the development packages?
Try 
sudo apt-get install libavahi-client-dev

**Comment by tiotp** [comment]
I am having the same issue on gentoo, even after cloning the libgeneral repository and running the listed commands. any help is appreciated!

**Comment by onny** [comment]
> configure:error: package requirements(libgeneral >= 39) were not met is disapper and i meet **other issue**: error wifi support requested but no wifi backebd could not be found. what should i do for it?

Please close this issue if your earlier error is resolved and open a new issue

**Comment by tihmstar** [comment]
Code has undergone a major rewrite since this issue was created.
