### ISSUE TITLE
How can I enable wifi sync with Libimobiledevice?

### ISSUE THREAD

**Issue by sprhawk** [tihmstar/usbmuxd2#3]
I know it is not related to this project directly, but I didn’t find any clue elsewhere. Did you have any clue?

Thanks

**Comment by tihmstar** [comment]
You can either use Xcode and tick "enable wifi sync" or you need to use this code https://github.com/tihmstar/libimobiledevice/blob/master/tools/idevicepair.c#L334-L340

**Comment by jkcoxson** [comment]
Could you maybe elaborate a bit more?

**Comment by dvc94ch** [comment]
@tihmstar can you open a PR against libimobiledevice with your wifi sync changes to `idevicepair`?
