### ISSUE TITLE
Can somebody do tutorial?

### ISSUE THREAD

**Issue by NintyS** [tihmstar/usbmuxd2#33]
Can somebody do tutorial how to set it? Because I builded usbmuxd2 and dependencies and I sill can't connect with my iPhone with ideviceinfo -n. IDK what the problem is.

**Comment by Blackspell01** [comment]
@NintyS have you found out what you wanted?

**Comment by NintyS** [comment]
Nah, I still don't know how to use it to see iPhones in local network :/

**Comment by Blackspell01** [comment]
I can't even install it ... I receive an error during make command

**Comment by NintyS** [comment]
What error? Maybe you don't have one of the packages? I know that in aur is build script, you can see there is you have everything you need
