### ISSUE TITLE
Daemon does not start if SystemConfiguration.plist does not exist

### ISSUE THREAD

**Issue by suaveolent** [tihmstar/usbmuxd2#6]
If the SystemConfiguration.plist file at /var/lib/lockdown does not exist, the daemon does not start.

It attempts to recreate the file, but fails (e.g. due to double free).

Damon needs to be started 4 times until the file has been recreated correctly.

**Comment by dominik-ziegler** [comment]
Probably duplicate of #2

**Comment by tihmstar** [comment]
Code has undergone a major rewrite since this issue was created.
