### ISSUE TITLE
Not able to build this on Raspbian Buster

### ISSUE THREAD

**Issue by canute4444** [tihmstar/usbmuxd2#8]
Getting this error when I try to build

> /usr/bin/ld: usbmuxd-Event.o: in function \`Event::~Event()':
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to \`__atomic_load_8'
/usr/bin/ld: /usr/include/c++/7/bits/atomic_base.h:396: undefined reference to \`__atomic_load_8'
/usr/bin/ld: usbmuxd-Event.o: in function \`Event::wait()':
/usr/include/c++/7/bits/atomic_base.h:296: undefined reference to \`__atomic_fetch_add_8'
/usr/bin/ld: /usr/include/c++/7/bits/atomic_base.h:304: undefined reference to \`__atomic_fetch_sub_8'
/usr/bin/ld: usbmuxd-Event.o: in function \`Event::members() const':
/usr/include/c++/7/bits/atomic_base.h:396: undefined reference to \`__atomic_load_8'
collect2: error: ld returned 1 exit status

Full log is here [https://pastebin.com/sNXnt0EM](https://pastebin.com/sNXnt0EM)

Did all the steps as per the README.
What am I doing wrong here?

**Comment by DeeMeyers** [comment]
If you're still interested, you can add `-latomic ` to end of the  AM_LDFLAGS line in usbmuxd2/Makefile.am. That has worked for me at least.

**Comment by bentumbler** [comment]
just a clarification.
This also needs to happen on libgeneral.

**Comment by tihmstar** [comment]
Code has undergone a major rewrite since this issue was created.
